// WARNING: DO NOT EDIT THIS FILE. It is autogenerated by Fresh.
import { IslandPreparer } from "fresh/internal";
import * as Header from "../islands/Header.tsx";
import * as Tabs from "../islands/Tabs.tsx";
import * as fsRoute_0 from "../routes/_app.tsx"

export const clientEntry = "/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/fresh-runtime.js"
export const version = "f90ad0a213f72552b339fa1c7fb148b830de1fe1"

export const islands = new Map();
const islandPreparer = new IslandPreparer();
islandPreparer.prepare(islands, Header, "/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/Header.js", "Header", []);
islandPreparer.prepare(islands, Tabs, "/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/Tabs.js", "Tabs", []);

export const staticFiles = new Map([
  ["/ava/ava.jpg", {"name":"/ava/ava.jpg","hash":"11344a8fcf05df6e01350b675650048d00e3998fba3da617d0cc560026f9f7e4","filePath":"static\\ava\\ava.jpg","contentType":"image/jpeg"}],
  ["/ava/ava.jxl", {"name":"/ava/ava.jxl","hash":"acdf82ea025b5001fc6dce711761b1319b6967929a397dc527baefbff4b9cb18","filePath":"static\\ava\\ava.jxl","contentType":"image/jxl"}],
  ["/ava/ava.webp", {"name":"/ava/ava.webp","hash":"4c4055fa7744b05485923aad2fc4f93ba85cb642dfd155db5369428c17c4f9ca","filePath":"static\\ava\\ava.webp","contentType":"image/webp"}],
  ["/ava/ava2.jpg", {"name":"/ava/ava2.jpg","hash":"8cb5cbaf6ad8957533c75057f9c93f568809c29c2755bad1a93589c602328cfb","filePath":"static\\ava\\ava2.jpg","contentType":"image/jpeg"}],
  ["/ava/ava2.jxl", {"name":"/ava/ava2.jxl","hash":"92b0c6b41ffe8b6b4ce2a5cc23ff7ab4965cd3003956078a3a28f476811c135a","filePath":"static\\ava\\ava2.jxl","contentType":"image/jxl"}],
  ["/ava/ava2.webp", {"name":"/ava/ava2.webp","hash":"86e7a2296b18521706d677cb9efd87ab079a443b2bef6e4897eaa51f8bd685df","filePath":"static\\ava\\ava2.webp","contentType":"image/webp"}],
  ["/favicon.ico", {"name":"/favicon.ico","hash":"ceefc31bd51194e03c78f9d35f9ca4d8b474b01280f83cd1490fb96a87c0dd12","filePath":"static\\favicon.ico","contentType":"image/vnd.microsoft.icon"}],
  ["/favicon.svg", {"name":"/favicon.svg","hash":"33b748dc8e4de2ec7fa9496fa9f4c608c57365e9a3ac72aaba1642c55260bc89","filePath":"static\\favicon.svg","contentType":"image/svg+xml"}],
  ["/googlea6d487357963a55e.html", {"name":"/googlea6d487357963a55e.html","hash":"93aced60605521e00192428a218791f7b0e08ab7671b6389f14e748e20af20c8","filePath":"static\\googlea6d487357963a55e.html","contentType":"text/html; charset=UTF-8"}],
  ["/Icon/arrow.tsx", {"name":"/Icon/arrow.tsx","hash":"94cdf1fc94a91988f7745588c48df0d0f40ab030d7652ba6ca0a4ba73196ada1","filePath":"static\\Icon\\arrow.tsx","contentType":"text/plain"}],
  ["/Icon/fresh-badge.tsx", {"name":"/Icon/fresh-badge.tsx","hash":"f56df67862ca2150e8a34298ff62f3c51953f46c933acd3e818fb7e46be890b1","filePath":"static\\Icon\\fresh-badge.tsx","contentType":"text/plain"}],
  ["/Icon/IcLogo.svg", {"name":"/Icon/IcLogo.svg","hash":"68e971c82f1e796c3f83944ecda54248dcad425dde5613bfdb4f46cf9afb7ba3","filePath":"static\\Icon\\IcLogo.svg","contentType":"image/svg+xml"}],
  ["/Icon/link.tsx", {"name":"/Icon/link.tsx","hash":"ab3b9e5af22997040bf7fa4ca6be885514b96b1763aa648544281ffd3c1f871e","filePath":"static\\Icon\\link.tsx","contentType":"text/plain"}],
  ["/Icon/social/gitea.tsx", {"name":"/Icon/social/gitea.tsx","hash":"631478ec13b3416b2efb3e635263ad8dfb9dbd1b92fa19beef074ca78227f85d","filePath":"static\\Icon\\social\\gitea.tsx","contentType":"text/plain"}],
  ["/Icon/social/Instagram.tsx", {"name":"/Icon/social/Instagram.tsx","hash":"a1e0d90c895e3668bdae59fac2c09adb903f31f48ad450423fb38ffb6c3a7a17","filePath":"static\\Icon\\social\\Instagram.tsx","contentType":"text/plain"}],
  ["/Icon/social/telegram.tsx", {"name":"/Icon/social/telegram.tsx","hash":"7928a47838cc2b7a256e0f98f85a0b48f5283df56019ad15e67941e0ccfd7caf","filePath":"static\\Icon\\social\\telegram.tsx","contentType":"text/plain"}],
  ["/Icon/star.tsx", {"name":"/Icon/star.tsx","hash":"3e34f84597e2fe172b097b29bf1740a97b158fca9d8f42a9f8e52e25837df0c5","filePath":"static\\Icon\\star.tsx","contentType":"text/plain"}],
  ["/Icon/tables.tsx", {"name":"/Icon/tables.tsx","hash":"9c3a13794f46ea7cd5febb4423588bc785f3bee2cae95d7f8de69c91437e6136","filePath":"static\\Icon\\tables.tsx","contentType":"text/plain"}],
  ["/img/interests/coding_item.svg", {"name":"/img/interests/coding_item.svg","hash":"031f2bd6a87cbc0deb5362d34d7380a700ba94ae201cbb0dd0f52e5d174425c7","filePath":"static\\img\\interests\\coding_item.svg","contentType":"image/svg+xml"}],
  ["/img/interests/crypto_item.svg", {"name":"/img/interests/crypto_item.svg","hash":"3a22e38f10d99d8eeaa742ebeddb3a4f31d70591f0cd7c7e1b6ae3b227bbaaea","filePath":"static\\img\\interests\\crypto_item.svg","contentType":"image/svg+xml"}],
  ["/img/interests/fitness_item.svg", {"name":"/img/interests/fitness_item.svg","hash":"1f0b3ee76017262315c2b5b701fba9fd91c3b742e95c28efa3e87d8770d1ef21","filePath":"static\\img\\interests\\fitness_item.svg","contentType":"image/svg+xml"}],
  ["/img/interests/games_item.svg", {"name":"/img/interests/games_item.svg","hash":"1de25280f764451a210159ada7c6b2011ef406d6966df2dcf1278001351f6249","filePath":"static\\img\\interests\\games_item.svg","contentType":"image/svg+xml"}],
  ["/logo.svg", {"name":"/logo.svg","hash":"88326af48312af7e16ebc06b03e8fec2750d09bf928bc90fa9280bf7cea07137","filePath":"static\\logo.svg","contentType":"image/svg+xml"}],
  ["/robots.txt", {"name":"/robots.txt","hash":"132550651c536c63f4646eb748c7ef7468b662bf7ac23ccfcd7a0fa3eeeb0c51","filePath":"static\\robots.txt","contentType":"text/plain; charset=UTF-8"}],
  ["/sitemap.xml", {"name":"/sitemap.xml","hash":"0ee5397186894bae8706385e53f6e801bd0f22105249046290c932c05d7ee093","filePath":"static\\sitemap.xml","contentType":"application/xml"}],
  ["/yandex_b66fe7e133b375ac.html", {"name":"/yandex_b66fe7e133b375ac.html","hash":"1fc64b2cbd562f33274dc2ea822e68501debb0aa498e19c09ee4a8b413d3e02f","filePath":"static\\yandex_b66fe7e133b375ac.html","contentType":"text/html; charset=UTF-8"}],
  ["/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/fresh-runtime.js", {"name":"/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/fresh-runtime.js","hash":"+A2NixkaN6c","filePath":"_fresh\\static\\_fresh\\js\\f90ad0a213f72552b339fa1c7fb148b830de1fe1\\fresh-runtime.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/Header.js", {"name":"/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/Header.js","hash":"jsCNr+mUA6g","filePath":"_fresh\\static\\_fresh\\js\\f90ad0a213f72552b339fa1c7fb148b830de1fe1\\Header.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/Tabs.js", {"name":"/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/Tabs.js","hash":"b5rxVbocYkw","filePath":"_fresh\\static\\_fresh\\js\\f90ad0a213f72552b339fa1c7fb148b830de1fe1\\Tabs.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/chunk-KUVLWYIZ.js", {"name":"/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/chunk-KUVLWYIZ.js","hash":"JsObOvjS1Uc","filePath":"_fresh\\static\\_fresh\\js\\f90ad0a213f72552b339fa1c7fb148b830de1fe1\\chunk-KUVLWYIZ.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/chunk-HCYWZKA7.js", {"name":"/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/chunk-HCYWZKA7.js","hash":"8zUIQmqvBz4","filePath":"_fresh\\static\\_fresh\\js\\f90ad0a213f72552b339fa1c7fb148b830de1fe1\\chunk-HCYWZKA7.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/chunk-MQAWGMSU.js", {"name":"/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/chunk-MQAWGMSU.js","hash":"EZWoYBGchVc","filePath":"_fresh\\static\\_fresh\\js\\f90ad0a213f72552b339fa1c7fb148b830de1fe1\\chunk-MQAWGMSU.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/metafile.json", {"name":"/_fresh/js/f90ad0a213f72552b339fa1c7fb148b830de1fe1/metafile.json","hash":"3daf211466d120505bb234d7c2b4a27db28e5c8bd8a065b8f62ecd4b13e39397","filePath":"_fresh\\static\\_fresh\\js\\f90ad0a213f72552b339fa1c7fb148b830de1fe1\\metafile.json","contentType":"application/json; charset=UTF-8"}],
  ["/styles.css", {"name":"/styles.css","hash":"41f8d4dee954d0c7f38f815b85aab1d06f805a303c8b049b93d7852cc753a286","filePath":"_fresh\\static\\styles.css","contentType":"text/css; charset=UTF-8"}]
]);

export const entryAssets = [];

export const fsRoutes = [
  { id: "/_app", mod: fsRoute_0, type: "app", pattern: "*", routePattern: "*" },
  { id: "/index", mod: () => import("../routes/index.tsx"), type: "route", pattern: "/", routePattern: "/" },
  { id: "/about", mod: () => import("../routes/about.tsx"), type: "route", pattern: "/about", routePattern: "/about" },
  { id: "/api/[name]", mod: () => import("../routes/api/[name].tsx"), type: "route", pattern: "/api/:name", routePattern: "/api/:name" },
];
