// WARNING: DO NOT EDIT THIS FILE. It is autogenerated by Fresh.
import { IslandPreparer } from "fresh/internal";
import * as Header from "../islands/Header.tsx";
import * as Tabs from "../islands/Tabs.tsx";
import * as fsRoute_0 from "../routes/_app.tsx"

export const clientEntry = "/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/fresh-runtime.js"
export const version = "0834ff4fc38599a2a55c130a5015d6685d1323c9"

export const islands = new Map();
const islandPreparer = new IslandPreparer();
islandPreparer.prepare(islands, Header, "/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/Header.js", "Header", []);
islandPreparer.prepare(islands, Tabs, "/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/Tabs.js", "Tabs", []);

export const staticFiles = new Map([
  ["/ava/ava.jpg", {"name":"/ava/ava.jpg","hash":"11344a8fcf05df6e01350b675650048d00e3998fba3da617d0cc560026f9f7e4","filePath":"static\\ava\\ava.jpg","contentType":"image/jpeg"}],
  ["/ava/ava.jxl", {"name":"/ava/ava.jxl","hash":"acdf82ea025b5001fc6dce711761b1319b6967929a397dc527baefbff4b9cb18","filePath":"static\\ava\\ava.jxl","contentType":"image/jxl"}],
  ["/ava/ava.webp", {"name":"/ava/ava.webp","hash":"4c4055fa7744b05485923aad2fc4f93ba85cb642dfd155db5369428c17c4f9ca","filePath":"static\\ava\\ava.webp","contentType":"image/webp"}],
  ["/favicon.svg", {"name":"/favicon.svg","hash":"e5091b9b0d453639875464c6add57239bb005b31dd3da548515ddcad8bd72ebe","filePath":"static\\favicon.svg","contentType":"image/svg+xml"}],
  ["/googlea6d487357963a55e.html", {"name":"/googlea6d487357963a55e.html","hash":"93aced60605521e00192428a218791f7b0e08ab7671b6389f14e748e20af20c8","filePath":"static\\googlea6d487357963a55e.html","contentType":"text/html; charset=UTF-8"}],
  ["/Icon/arrow.tsx", {"name":"/Icon/arrow.tsx","hash":"0cfbe95c5cc0edb59b13d78c28223330bc2be6b2747bbe0f06fd0e77ef554cb1","filePath":"static\\Icon\\arrow.tsx","contentType":"text/plain"}],
  ["/Icon/fresh-badge.tsx", {"name":"/Icon/fresh-badge.tsx","hash":"5bf5747dc7fdcfde5beb7c63acdbc9796ec695965f62b5fee2d72485d8c413b5","filePath":"static\\Icon\\fresh-badge.tsx","contentType":"text/plain"}],
  ["/Icon/link.tsx", {"name":"/Icon/link.tsx","hash":"18065329501e52705eb44af96b093c949e4628b5be722437242c62e6b62f86b1","filePath":"static\\Icon\\link.tsx","contentType":"text/plain"}],
  ["/Icon/social/gitea.tsx", {"name":"/Icon/social/gitea.tsx","hash":"df9f0b7eb3d8b627efdb2d67b528417766dfe11f5636d188e3c5c73b90827fbe","filePath":"static\\Icon\\social\\gitea.tsx","contentType":"text/plain"}],
  ["/Icon/social/Instagram.tsx", {"name":"/Icon/social/Instagram.tsx","hash":"6570217a3a90ef344ca540d92759dad6f633ff559c9232c5482d874286a6c776","filePath":"static\\Icon\\social\\Instagram.tsx","contentType":"text/plain"}],
  ["/Icon/social/telegram.tsx", {"name":"/Icon/social/telegram.tsx","hash":"7fc7ce38b4bb807aad2b470ec8fc4ffedaca213ba99dc29398ae066c141e56f4","filePath":"static\\Icon\\social\\telegram.tsx","contentType":"text/plain"}],
  ["/Icon/star.tsx", {"name":"/Icon/star.tsx","hash":"a604949918899444ef0cf213b28805d62ccb51d35acbda5f8b2e7cde48541bef","filePath":"static\\Icon\\star.tsx","contentType":"text/plain"}],
  ["/Icon/tables.tsx", {"name":"/Icon/tables.tsx","hash":"e44020131c3f03a28329a5f7522233fda5a65c2063badd519292947d8bf42b8c","filePath":"static\\Icon\\tables.tsx","contentType":"text/plain"}],
  ["/img/interests/coding_item.svg", {"name":"/img/interests/coding_item.svg","hash":"d0db55c2f210293c3f862d22b10ac6552ff26093fa419b2acb0b756fb6db8e5f","filePath":"static\\img\\interests\\coding_item.svg","contentType":"image/svg+xml"}],
  ["/img/interests/crypto_item.svg", {"name":"/img/interests/crypto_item.svg","hash":"4f1cc055b2132b6c21514ac265ee031de70bd6d5a2eba7498d3755725dac616c","filePath":"static\\img\\interests\\crypto_item.svg","contentType":"image/svg+xml"}],
  ["/img/interests/fitness_item.svg", {"name":"/img/interests/fitness_item.svg","hash":"c1b2b23c24ae53f374b330324dc90b046652672e65fe063abf02ac62eae7b0af","filePath":"static\\img\\interests\\fitness_item.svg","contentType":"image/svg+xml"}],
  ["/img/interests/games_item.svg", {"name":"/img/interests/games_item.svg","hash":"d290571914af9a92fe9aefb053f8c3c7e1f95a1cd52fd52929805ea2752fd6ad","filePath":"static\\img\\interests\\games_item.svg","contentType":"image/svg+xml"}],
  ["/logo.svg", {"name":"/logo.svg","hash":"57a56c2eae18ee44be2439c29154a6fd398c4984d03eb1418a4e81cfbfc8e28f","filePath":"static\\logo.svg","contentType":"image/svg+xml"}],
  ["/robots.txt", {"name":"/robots.txt","hash":"c37e4f0276ae3400b7ad1a09984b1e8e1212cf30bf768928fd90fd1154050165","filePath":"static\\robots.txt","contentType":"text/plain; charset=UTF-8"}],
  ["/sitemap.xml", {"name":"/sitemap.xml","hash":"8615c0b0a4a3b6cfd305b939d4ccc8829ef19af879000949968480ab4803b4d1","filePath":"static\\sitemap.xml","contentType":"application/xml"}],
  ["/yandex_b66fe7e133b375ac.html", {"name":"/yandex_b66fe7e133b375ac.html","hash":"14e404a48ef0177ded5bafc86068e0b39d2aa8e491aee4cba9357380b2a33a4d","filePath":"static\\yandex_b66fe7e133b375ac.html","contentType":"text/html; charset=UTF-8"}],
  ["/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/fresh-runtime.js", {"name":"/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/fresh-runtime.js","hash":"eE4oLMoSpHQ","filePath":"_fresh\\static\\_fresh\\js\\0834ff4fc38599a2a55c130a5015d6685d1323c9\\fresh-runtime.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/Header.js", {"name":"/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/Header.js","hash":"jsCNr+mUA6g","filePath":"_fresh\\static\\_fresh\\js\\0834ff4fc38599a2a55c130a5015d6685d1323c9\\Header.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/Tabs.js", {"name":"/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/Tabs.js","hash":"b5rxVbocYkw","filePath":"_fresh\\static\\_fresh\\js\\0834ff4fc38599a2a55c130a5015d6685d1323c9\\Tabs.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/chunk-KUVLWYIZ.js", {"name":"/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/chunk-KUVLWYIZ.js","hash":"JsObOvjS1Uc","filePath":"_fresh\\static\\_fresh\\js\\0834ff4fc38599a2a55c130a5015d6685d1323c9\\chunk-KUVLWYIZ.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/chunk-HCYWZKA7.js", {"name":"/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/chunk-HCYWZKA7.js","hash":"8zUIQmqvBz4","filePath":"_fresh\\static\\_fresh\\js\\0834ff4fc38599a2a55c130a5015d6685d1323c9\\chunk-HCYWZKA7.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/chunk-MQAWGMSU.js", {"name":"/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/chunk-MQAWGMSU.js","hash":"EZWoYBGchVc","filePath":"_fresh\\static\\_fresh\\js\\0834ff4fc38599a2a55c130a5015d6685d1323c9\\chunk-MQAWGMSU.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/metafile.json", {"name":"/_fresh/js/0834ff4fc38599a2a55c130a5015d6685d1323c9/metafile.json","hash":"9e1b724055690738d84a3c598b0d9ab36ef31e718c2541fcc65585b54d7245c1","filePath":"_fresh\\static\\_fresh\\js\\0834ff4fc38599a2a55c130a5015d6685d1323c9\\metafile.json","contentType":"application/json; charset=UTF-8"}],
  ["/styles.css", {"name":"/styles.css","hash":"8ec4ca53195a66bcc80b5a085ddaed9ce1723a3eb1592da994123d861d9c2a70","filePath":"_fresh\\static\\styles.css","contentType":"text/css; charset=UTF-8"}]
]);

export const entryAssets = [];

export const fsRoutes = [
  { id: "/_app", mod: fsRoute_0, type: "app", pattern: "*", routePattern: "*" },
  { id: "/index", mod: () => import("../routes/index.tsx"), type: "route", pattern: "/", routePattern: "/" },
  { id: "/about", mod: () => import("../routes/about.tsx"), type: "route", pattern: "/about", routePattern: "/about" },
  { id: "/api/[name]", mod: () => import("../routes/api/[name].tsx"), type: "route", pattern: "/api/:name", routePattern: "/api/:name" },
];
